spring.application.name=web_term_2026
server.servlet.context-path=/dgjs

# ==========================================
# File Upload Configuration
# ==========================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=D:/upload

# Custom directory property for ResourceConfig
file.dir=D:/upload/

# Tomcat limits
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB